### PR TITLE
Aftab ahmed abro patch 2

### PR DESCRIPTION
**Pull request by AftabAhmedAbro**
Index file on TypeScript for the project

### CODE REVIEW

**Comment by AftabAhmedAbro** [comment]
Index file on TypeScript for the project

**Comment by AftabAhmedAbro** [comment]
Index file on TypeScript for the project

**Comment by HaseebUllahAbbasi** [comment]
what actually are you trying to achieve aftab in this project ?

**Comment by HaseebUllahAbbasi** [comment]
i couldn't figure it out, you added just index file with package.json and then added solidity file , I am reverting it as please be specific.

**Comment by HaseebUllahAbbasi** [comment]
please write commit message with meaningful message, as " init setp for backend ", " init setp for front end", " added mongoose operations on backend to persist data on localhost "    like this

**Pull request merged**
